### ISSUE TITLE
WhatsApp conversation list not blur

### ISSUE THREAD

**Issue by davidt99** [dcohenb/whatsapp-incognito#1]
It seems that whatsapp web change something and the conversation list is no longer blurred
I'm referring to [this](https://chrome.google.com/webstore/detail/webchats-incognito-mode/lapmmaaniipbdelgagpdaplgfagojkfo?utm_source=chrome-app-launcher-info-dialog) chrome extension.

**Comment by dcohenb** [comment]
Hi @davidt99 thanks for the input. the issue was just fixed.
please allow up to 24 hours for chrome to update the extension

**Comment by davidt99** [comment]
Hi,
It's been almost a week and I'm still having the issue.
I'm using chrome on linux if it helps.
